# -*- coding: utf-8 -*-
"""Export an mWater form design as a readable review document.

Written so the SDWS 26 instrument can be put to the Head of Carbon without him
opening mWater: question text in every language the form declares, choices,
skip logic in plain words, and the parameter each question serves where the
question or its hint says so.

The parameter column is read from what the form itself states - a hint naming
"SDWS 26", or a question code - and is left blank when the form does not say.
It is not inferred, because a review document that guesses which parameter a
question serves is worse than one that admits it does not know.

    python3 tools/export_form_review.py <form_id> <out.md>
"""
import json, os, re, subprocess, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLI = os.path.expanduser("~/mwater-mcp/cli_call.mjs")
QT = ("Question",)


def fetch(form_id):
    r = subprocess.run(["node", CLI, "mwater_get_form_design",
                        json.dumps({"form_id": form_id})],
                       capture_output=True, text=True, cwd=os.path.dirname(CLI))
    s = r.stdout
    if "{" not in s:
        sys.exit(f"could not read form {form_id}: {(r.stderr or s)[:200]}")
    return json.loads(s[s.index("{"):])


def loc(d, code):
    return (d or {}).get(code) or ""


def param_of(q):
    """The parameter this question serves, as the FORM states it. Never guessed."""
    blob = json.dumps(q.get("text") or {}) + json.dumps(q.get("hint") or {})
    m = re.search(r"SDWS\s*(\d+)", blob)
    return f"SDWS {m.group(1)}" if m else ""


def conditions(q, byid):
    out = []
    for c in q.get("conditions") or []:
        src = (c.get("lhs") or {}).get("question")
        t = byid.get(src, {})
        label = loc(t.get("text"), "en") or loc(t.get("text"), "fr") or src or "?"
        op = {"isoneof": "is one of", "is": "is", "isnt": "is not"}.get(c.get("op"), c.get("op"))
        lit = (c.get("rhs") or {}).get("literal")
        vals = lit if isinstance(lit, list) else [lit]
        names = []
        for v in vals:
            ch = next((ch for ch in (t.get("choices") or []) if ch.get("id") == v), None)
            names.append(loc((ch or {}).get("label"), "en")
                         or loc((ch or {}).get("label"), "fr") or str(v))
        out.append(f'shown when "{label[:60]}" {op} {", ".join(names)}')
    return out


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: export_form_review.py <form_id> <out.md>")
    fid, out_path = sys.argv[1], sys.argv[2]
    doc = fetch(fid)
    design = doc["design"]
    locales = [l["code"] for l in design.get("locales") or []]

    items, byid = [], {}
    def walk(n, sec, grp):
        if isinstance(n, list):
            for x in n:
                walk(x, sec, grp)
            return
        if not isinstance(n, dict):
            return
        t = n.get("_type") or ""
        if t == "Section":
            sec = loc(n.get("name"), "fr") or loc(n.get("name"), "en") or sec
        if t == "Group":
            grp = loc(n.get("name"), "fr") or loc(n.get("name"), "en") or grp
        if "Question" in t or t == "Instructions":
            byid[n.get("_id")] = n
            items.append((sec, grp, n))
        for v in n.values():
            if isinstance(v, (list, dict)):
                walk(v, sec, grp)
    walk(design.get("contents"), None, None)

    L = []
    name = loc(design.get("name"), design.get("name", {}).get("_base") or "en") \
        or doc.get("name") or fid
    L.append(f"# {name}\n")
    L.append(f"**Form id** `{fid}` · **revision** {doc.get('_rev')} · "
             f"**state** {doc.get('state')}\n")
    L.append(f"**Languages declared:** {', '.join(locales) or 'none'}\n")
    deps = doc.get("deployments") or []
    if deps:
        L.append("**Deployments:** " + ", ".join(
            f"{d.get('name')}{' (active)' if d.get('active') else ''}" for d in deps) + "\n")
    q_only = [x for x in items if "Question" in (x[2].get("_type") or "")]
    L.append(f"**{len(q_only)} questions.** Generated by "
             f"`tools/export_form_review.py`; nothing here is typed by hand.\n")
    L.append("\n---\n")

    cur_sec = cur_grp = object()
    for sec, grp, q in items:
        if sec != cur_sec:
            L.append(f"\n## {sec or 'Ungrouped'}\n")
            cur_sec, cur_grp = sec, object()
        if grp != cur_grp:
            if grp:
                L.append(f"\n### {grp}\n")
            cur_grp = grp
        t = q.get("_type") or ""
        if t == "Instructions":
            txt = loc(q.get("text"), "fr") or loc(q.get("text"), "en")
            L.append(f"\n> {re.sub(r'<[^>]+>', '', txt)}\n")
            continue
        code = q.get("code") or "—"
        par = param_of(q)
        flags = []
        if q.get("required"):
            flags.append("required")
        if q.get("disabled"):
            flags.append("**disabled — does not render**")
        head = f"\n**{code}** · {t.replace('Question', '')}"
        if par:
            head += f" · serves **{par}**"
        if flags:
            head += " · " + ", ".join(flags)
        L.append(head + "\n")
        for lc in locales:
            v = loc(q.get("text"), lc)
            if v:
                L.append(f"- *{lc}*: {v}\n")
        h = q.get("hint") or {}
        for lc in locales:
            if loc(h, lc):
                L.append(f"    - hint (*{lc}*): {loc(h, lc)}\n")
        for c in conditions(q, byid):
            L.append(f"    - {c}\n")
        for ch in q.get("choices") or []:
            lab = " / ".join(filter(None, (loc(ch.get("label"), lc) for lc in locales)))
            L.append(f"    - `{ch.get('id')}` {lab}\n")

    open(out_path, "w", encoding="utf8").write("".join(L))
    print(f"{len(q_only)} questions -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
