# -*- coding: utf-8 -*-
"""Which generator writes each field of the page's embedded data.

Established by experiment, not by reading the code: every numeric and free-text
leaf in the embedded objects was perturbed, the whole generator chain was run,
and a field that came back has a generator that computes it. A field that kept
the perturbation has none - nothing in the build can move it. That is the
S.wq_tested fault, and it was true of 71 fields when this was written.

GENERATED   the tool that recomputes it every build.
POPULATION  a population in populations.py reproduces it exactly; the gate
            asserts the stored value against the population size.
UNTESTABLE  the perturbation was a no-op (a date, an id, a hash, a boolean),
            so this method cannot decide. Listed, not excused.

Anything absent from all three is unregistered and the gate fails.
"""

GENERATED = {
    # recomputed for every portfolio pump each build (23 September)
    'PUMPS.[].wq': 'rebuild_pump_inputs',
    'PUMPS.[].wq_date': 'rebuild_pump_inputs',
    'PUMPS.[].wq_status': 'rebuild_pump_inputs',
    'PUMPS.[].benef': 'rebuild_pump_inputs',
    'DOWN.[].wq': 'rebuild_pump_inputs',
    'DOWN.[].wq_date': 'rebuild_pump_inputs',
    'DOWN.[].wq_status': 'rebuild_pump_inputs',
    'DOWN.[].benef': 'rebuild_pump_inputs',
    'CALS.custody': 'calendar_stratum',
    'FORMSNAP.fetched': 'refresh_form_snapshot',
    'FORMSNAP.forms': 'refresh_form_snapshot',
    'FORMSNAP.questions': 'refresh_form_snapshot',
    'FORMSNAP.rev': 'refresh_form_snapshot',
    'TTRQ.all': 'render_ttr_table',
    'TTRQ.by_quarter': 'render_ttr_table',
    'TTRQ.by_site': 'render_ttr_table',
    'TTRQ.note': 'render_ttr_table',
    'NEAREST.note': 'check_distances',
    'NEAREST.population': 'check_distances',
    'NEAREST.computed': 'check_distances',
    'NEAREST.distances': 'check_distances',
    'CALS.by_site': 'calendar_stratum',
    'CALS.by_year': 'calendar_stratum',
    'CALS.evidenced_by': 'calendar_stratum',
    'CALS.evidenced_points': 'calendar_stratum',
    'CALS.first_reader': 'calendar_stratum',
    'CALS.floor_pct': 'calendar_stratum',
    'CALS.generator': 'calendar_stratum',
    'CALS.input': 'calendar_stratum',
    'CALS.input_run_on': 'calendar_stratum',
    'CALS.input_written_by': 'calendar_stratum',
    'CALS.mean_do_by_photos': 'calendar_stratum',
    'CALS.note': 'calendar_stratum',
    'CALS.photographs': 'calendar_stratum',
    'CALS.portfolio': 'calendar_stratum',
    'CALS.seed': 'calendar_stratum',
    'CALS.year_coverage': 'calendar_stratum',
    'WPOPX.barrier_exclusion': 'wpop_pipeline_figures',
    'WPOPX.generator': 'wpop_pipeline_figures',
    'WPOPX.note': 'wpop_pipeline_figures',
    'WPOPX.pipeline': 'wpop_pipeline_figures',
    'WPOPX.runs': 'wpop_pipeline_figures',
    'WPOPX.seed': 'wpop_pipeline_figures',
    'WPOPX.streams_as_barriers_delta': 'wpop_pipeline_figures',
    'WPOPX.streams_as_barriers_delta_pct': 'wpop_pipeline_figures',

    'SDWS26.answered_both': 'rebuild_sdws26',
    'SDWS26.approved': 'rebuild_sdws26',
    'SDWS26.excluded_part_entries': 'rebuild_sdws26',
    'SDWS26.excluded_answered_max': 'rebuild_sdws26',
    'SDWS26.excluded_answered_min': 'rebuild_sdws26',
    'SDWS26.form': 'rebuild_sdws26',
    'SDWS26.min_clusters': 'rebuild_sdws26',
    'SDWS26.q_dry': 'rebuild_sdws26',
    'SDWS26.q_rain': 'rebuild_sdws26',
    'SDWS26.responses_total': 'rebuild_sdws26',
    'SDWS26.round_from': 'rebuild_sdws26',
    'SDWS26.round_to': 'rebuild_sdws26',
    'SDWS26.rule_difference': 'rebuild_sdws26',
    'SDWS26.scenarios': 'rebuild_sdws26',
    'SDWS26.served_both_seasons': 'rebuild_sdws26',
    'SDWS26.served_choices': 'rebuild_sdws26',
    'SDWS26.served_dry': 'rebuild_sdws26',
    'SDWS26.served_either_season': 'rebuild_sdws26',
    'SDWS26.served_rain': 'rebuild_sdws26',
    'SDWS26.statuses': 'rebuild_sdws26',

    'WPOPMETA.points_at_the_cap': 'check_wpopmeta (data/sdws1_summary_equal.json)',
    'WPOPMETA.points_cut_over_10pct': 'check_wpopmeta (data/sdws1_summary_equal.json)',
    'WPOPMETA.points_with_a_barrier': 'check_wpopmeta (data/sdws1_summary_equal.json)',
    'WPOPMETA.raster': 'check_wpopmeta (data/sdws1_summary_equal.json)',
    'WPOPMETA.raster_national_sum': 'check_wpopmeta (data/sdws1_summary_equal.json)',
    'WPOPMETA.rows': 'check_wpopmeta (data/sdws1_summary_equal.json)',

    'PARTIAL.[].kind_basis': 'build_call_tables',
    'DOWN.[].commune': 'rebuild_summary',
    'DOWN.[].fkt': 'rebuild_summary',
    'DOWN.[].lat': 'rebuild_summary',
    'DOWN.[].lon': 'rebuild_summary',
    'DOWN.[].pump': 'rebuild_summary',
    'DOWN.[].site': 'rebuild_summary',
    'METRICS.points_no_works_record': 'rebuild_summary',
    'METRICS.points_over_6_months': 'rebuild_summary',
    'PUMPS.[].commune': 'rebuild_summary',
    'PUMPS.[].fkt': 'rebuild_summary',
    'PUMPS.[].lat': 'rebuild_summary',
    'PUMPS.[].lon': 'rebuild_summary',
    'PUMPS.[].pump': 'rebuild_summary',
    'PUMPS.[].site': 'rebuild_summary',
    'S.by_pump': 'rebuild_summary',
    'S.by_site': 'rebuild_summary',
    'S.down_list': 'rebuild_summary',
    'S.wq_untested': 'rebuild_summary',

    'TTR.ttr_2026': 'rebuild_ttr',
    'TTR.ttr_3d': 'rebuild_ttr',
    'TTR.ttr_7d': 'rebuild_ttr',
    'TTR.ttr_Fort-Dauphin': 'rebuild_ttr',
    'TTR.ttr_Maroantsetra': 'rebuild_ttr',
    'TTR.ttr_mean': 'rebuild_ttr',
    'TTR.ttr_median': 'rebuild_ttr',
    'TTR.ttr_n': 'rebuild_ttr',

    'ACTN.act': 'render_datasets',
    'ACTN.closed': 'render_datasets',
    'ACTN.nodate': 'render_datasets',
    'ACTN.open': 'render_datasets',
    'ACTN.overdue': 'render_datasets',
    'ACTN.rows': 'render_datasets',
    'ACTN.watch': 'render_datasets',
    'CALX.basis': 'render_datasets',
    'CALX.days_illegible': 'render_datasets',
    'CALX.days_not_operational': 'render_datasets',
    'CALX.days_unobserved': 'render_datasets',
    'CALX.images_readable': 'render_datasets',
    'CALX.images_with_day_calls': 'render_datasets',
    'CALX.implied_days_not_operational': 'render_datasets',
    'CALX.implied_true_marked_pct': 'render_datasets',
    'CALX.implied_uptime_days': 'render_datasets',
    'CALX.impossible_cells': 'render_datasets',
    'CALX.median_confidence': 'render_datasets',
    'CALX.observed_cells': 'render_datasets',
    'CALX.observed_illegible': 'render_datasets',
    'CALX.observed_illegible_pct': 'render_datasets',
    'CALX.observed_marked': 'render_datasets',
    'CALX.observed_marked_pct': 'render_datasets',
    'CALX.photographs_excluded_not_calendar': 'render_datasets',
    'CALX.photographs_held': 'render_datasets',
    'CALX.photographs_total': 'render_datasets',
    'CALX.points_total': 'render_datasets',
    'CALX.points_without_readable': 'render_datasets',
    'CALX.probe_cells': 'render_datasets',
    'CALX.probe_marked_pct': 'render_datasets',
    'CALX.pump_periods': 'render_datasets',
    'CALX.sheets_by_year': 'render_datasets',
    'CALX.sheets_dated_from_the_sheet': 'render_datasets',
    'CALX.sheets_not_dated': 'render_datasets',
    'CALX.unobserved_called_illegible': 'render_datasets',
    'CALX.unobserved_called_marked': 'render_datasets',
    'CALX.unobserved_cells': 'render_datasets',
    'CALX.visits_total': 'render_datasets',
    'CALX.visits_with_readable': 'render_datasets',
    'CALX.visits_without_readable': 'render_datasets',
    'CALX.water_points': 'render_datasets',
    'CARBON.basis': 'render_datasets',
    'CARBON.carbon_2026_coverage_pct': 'render_datasets',
    'CARBON.carbon_points': 'render_datasets',
    'CARBON.carbon_points_with_2026_sheet': 'render_datasets',
    'CARBON.carbon_points_without_2026_sheet': 'render_datasets',
    'CARBON.sheets_2026_outside_the_fleet': 'render_datasets',
    'CARBON.supersedes': 'render_datasets',
    'DOWN.[].days_down': 'build_call_tables',
    'DOWN.[].status': 'build_call_tables',
    'DOWN.[].status_src': 'build_call_tables',
    'ENDURO.people': 'render_enduro',
    'ENDURO.reg': 'render_enduro',
    'ENDURO.systems': 'render_enduro',
    'ENDURO_SRC.age': 'render_enduro',
    'ENDURO_SRC.by': 'render_enduro',
    'ENDURO_SRC.doc': 'render_enduro',
    'ENDURO_SRC.max': 'render_enduro',
    'ENDURO_SRC.people_by': 'render_enduro',
    'FRESH.blocking_lag_days': 'render_datasets',
    'FRESH.files_age_days': 'render_datasets',
    'FRESH.lag_days': 'render_datasets',
    'FRESH.page_age_days': 'render_datasets',
    'FRESH.page_behind_files_days': 'render_datasets',
    'FRESH.per_source': 'render_datasets',
    'FRESH.worst_source': 'render_datasets',
    'FRESH.worst_source_lag_days': 'render_datasets',
    'METRICS.calls_using_service_visit_choice': 'render_datasets',
    'METRICS.consent_question_answers': 'render_datasets',
    'METRICS.downs_without_repair': 'render_datasets',
    'METRICS.duplicate_question_codes': 'render_datasets',
    'METRICS.enduro_figures_age_days': 'render_datasets',
    'METRICS.enduro_figures_unattributed': 'render_datasets',
    'METRICS.er_percent_of_type3_cap': 'render_datasets',
    'METRICS.extract_lag_days': 'render_datasets',
    'METRICS.marolinta_blank_status': 'render_datasets',
    'METRICS.marolinta_new_borehole_records': 'render_datasets',
    'METRICS.marolinta_new_final': 'render_datasets',
    'METRICS.marolinta_points_no_admin': 'render_datasets',
    'METRICS.marolinta_points_no_photograph': 'render_datasets',
    'METRICS.marolinta_points_without_wq': 'render_datasets',
    'METRICS.marolinta_rehabs_final': 'render_datasets',
    'METRICS.marolinta_three_points_no_photograph': 'render_datasets',
    'METRICS.moramanga_draft_records': 'render_datasets',
    'METRICS.photographs_misfiled': 'render_datasets',
    'METRICS.point_742896839_in_register': 'render_datasets',
    'METRICS.points_no_2026_calendar': 'render_datasets',
    'METRICS.points_no_calendar_ever': 'render_datasets',
    'METRICS.points_without_readable_calendar': 'render_datasets',
    'METRICS.pumps_reduced_performance': 'render_datasets',
    'METRICS.register_dashboard_gap': 'render_datasets',
    'METRICS.sites_without_route_plan': 'render_datasets',
    'METRICS.stroke_test_responses': 'render_datasets',
    'METRICS.transcription_sheets_done': 'render_datasets',
    'METRICS.unapproved_works_records': 'render_datasets',
    'METRICS.unsourced_figures': 'render_datasets',
    'METRICS.usage_question_answers': 'render_datasets',
    'METRICS.usage_survey_responses': 'render_datasets',
    'METRICS.water_quality_failures_unretested': 'render_datasets',
    'PARTIAL.[].comments': 'build_call_tables',
    'PARTIAL.[].commune': 'build_call_tables',
    'PARTIAL.[].kind': 'build_call_tables',
    'PARTIAL.[].site': 'build_call_tables',
    'PARTIAL.[].status': 'build_call_tables',
    'POPS.chain': 'render_derivations',
    'POPS.gaps': 'render_derivations',
    'POPS.populations': 'render_derivations',
    'PUMPS.[].days': 'rebuild_activity',
    'PUMPS.[].status': 'build_call_tables',
    'PUMPS.[].status_src': 'build_call_tables',
    'S.over6': 'rebuild_activity',
    'S.over6_site': 'rebuild_activity',
    'S.status': 'build_call_tables',
    'S.week': 'rebuild_activity',
    # 25 September: perturbed one leaf of each, ran the generator, the value came back
    'TTRQ.facts': ('render_ttr_table', 'render_datasets'),
    'ENDURO.disp': 'render_enduro',
    'DERIV_RULES.[].re': 'render_derivations',
    'DERIV_RULES.[].pop': 'render_derivations',
    'DERIV_RULES.[].what': 'render_derivations',
    'DERIV_RULES.[].forms': 'render_derivations',
    'DERIV_RULES.[].why': 'render_derivations',
    'VINTAGE.checked': 'render_datasets',
    'VINTAGE.data_to': 'render_datasets',
    'VINTAGE.last_record_by_source': 'render_datasets',
    'VINTAGE.newest_pull': 'render_datasets',
    'VINTAGE.note': 'render_datasets',
    'VINTAGE.oldest_sources': 'render_datasets',
    'VINTAGE.per_extract': 'render_datasets',
    'VINTAGE.spread_days': 'render_datasets',
    'HOLDS.n': 'render_datasets',
    'HOLDS.cut_used': 'render_datasets',
    'NOTCAL.total': 'render_datasets',
    'NOTCAL.by_reason': 'render_datasets',
    'NOTCAL.by_question': 'render_datasets',
    'NOTCAL.accepted': 'render_datasets',
    'NOUSABLE.total': 'render_datasets',
    'NOUSABLE.by_category': 'render_datasets',
    'VMAP.divergences': 'render_datasets',
    'VMAP.action_now': 'render_datasets',
}

# Objects keyed by something that changes week to week (an extract file, an
# action id), rebuilt whole by one generator: every key is covered. Each was
# perturbed and came back on 25 September.
WHOLE = {
    'PULLS': 'render_datasets',     # data/extract_manifest.json, one key per extract
    'ACTCOND': 'render_datasets',   # data-kind conditions, one key per action
    # the piped water-quality figures, keyed by system code
    'PIPEDWQ': ('rebuild_piped_wq', 'render_datasets'),
}

POPULATION = {
    'S.n': 'managed_fleet',
    # the register block: written each build by tools/sync_reg_populations.py
    'REG.succ': 'rehabilitated_successfully',
    'REG.succ_records': 'successful_first_rehabilitation_records',
    'REG.total_first_rehab': 'first_rehabilitation_records',
    'REG.final_records': 'first_rehabilitation_records_final',
    'REG.fail': 'first_rehab_recorded_unsuccessful',
    'REG.blank': 'first_rehab_success_blank',
    'REG.marolinta_new': 'marolinta_new_constructions',
    'REG.marolinta_rehab': 'marolinta_rehabilitations',
    'S.wq_tested': 'water_quality_tested',
}

# Perturbation could not move these, so the experiment is silent on them.
UNTESTABLE = {
    'CORR.version',
    'DOWN.[].comm',
    'DOWN.[].due',
    'DOWN.[].last_pm',
    'DOWN.[].last_repair',
    'DOWN.[].last_visit',
    'DOWN.[].last_visit_real',
    'DOWN.[].nocomm',
    'DOWN.[].status_date',
    'DOWN.[].wp',
    'ENDURO_SRC.as_at',
    'ENDURO_SRC.people_as_at',
    'ENDURO_SRC.reg_as_at',
    'ENDURO_SRC.stale',
    'FRESH.checked',
    'FRESH.extract_newest',
    'FRESH.files_newest',
    'FRESH.known_gaps',
    'FRESH.latest_in_extract',
    'FRESH.latest_in_extract_files',
    'FRESH.latest_in_mwater',
    'FRESH.mwater_newest',
    'METRICS.enduro_sites_outside_mwater',
    'OPENREP.[].date',
    'OPENREP.[].wp',
    'PARTIAL.[].date',
    'PARTIAL.[].rid',
    'PARTIAL.[].wp',
    'POPS.form_base',
    'PUMPS.[].comm',
    'PUMPS.[].due',
    'PUMPS.[].last_pm',
    'PUMPS.[].last_repair',
    'PUMPS.[].last_visit',
    'PUMPS.[].last_visit_real',
    'PUMPS.[].nocomm',
    'PUMPS.[].status_date',
    'PUMPS.[].wp',
    'RESP.{*}.h',
    'RESP.{*}.p',
    'RESP.{*}.q',
    'RESP.{*}.v',
    'S.wq_fail',
    'WPOPMETA.barriers_applied',
    'WPOPMETA.folder',
    'WPOPMETA.raster_sha256',
    'WPOPMETA.run',
}


def resolve(obj, field):
    """The generator for one field, or None when nothing writes it."""
    key = f"{obj}.{field}"
    if key in GENERATED:
        g = GENERATED[key]
        return g if isinstance(g, str) else "+".join(g)
    if key in POPULATION:
        return f"population:{POPULATION[key]}"
    if key in UNTESTABLE:
        return "untestable"
    if obj in WHOLE:
        return WHOLE[obj]
    return None


GENERATORS = GENERATED  # legacy name
